# See: https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "egpu"
version = "0.0.0"
authors = ["Arto Bendiken"]
edition = "2024"
#rust-version = "1.85"
description = "Libegpu is a work in progress"
#documentation = ""
readme = true
homepage = "https://libegpu.dev"
repository = "https://github.com/artob/libegpu"
license = "Unlicense"
keywords = ["egpu", "gpu", "pcie", "usb"]
categories = ["hardware-support"]
publish = true

[features]
default = ["all", "std"]
all = ["pci", "usb"]
std = ["derive_more/std"]

# Optional features:
pci = ["dep:pci-info"]
usb = ["dep:nusb"]

[build-dependencies]

[dependencies]
nusb = { version = "0.2", optional = true }
pci-info = { version = "0.3", optional = true }
derive_more = { version = "2", default-features = false, features = ["display"] }

[patch.crates-io]

[profile.release]
opt-level = "z"
strip = true
lto = "thin"

[[bin]]
name = "egpu"
path = "src/main.rs"
